# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Gun.create([{ name: 'Fio dental' },
  { name: 'Saquinho de chá' },
  { name: 'Bolinha de tênis' },
  { name: 'Nerf do Gabriel' },
  { name: 'Ventilador do Gabriel' },
  { name: 'Pote de mantega' },
  { name: 'Puff' },
  { name: 'Bolacha cream cracker' },
  { name: 'Guarda-chuva' },
  { name: 'Molho de chaves' },
  { name: 'Presunto' },
  { name: 'Grampeador' },
  { name: 'Lixeira' },
  { name: 'Computador' },
  { name: 'Mouse' },
  { name: 'Caneta' },
  { name: 'Telefone' },
  { name: 'Rolo de papel higiênico' },
  { name: 'Bolinha de ping-pong' },
  { name: 'Linx copo' },
  { name: 'Pote de margarina' },
  { name: 'Almofada do sofá' },
  { name: 'Banana' },
  { name: 'Controle do ar condicionado' },
  { name: 'Controle de playstation' },
  { name: 'Barril de chopp' },
  { name: 'Caneca gigante do Oriani' },
  { name: 'Raquete de ping-pong' },
  { name: 'Almofada das poltronas da sala de reunião' },
  { name: 'Gatinho desenhado num papel A4' },
  { name: 'Almofada roxa escrito amor' },
  { name: 'Caixa de chá mate' },
  { name: 'Tampa do reservatorio de café da cafeteira' },
  { name: 'Chinelo do Gabriel' },
  { name: 'Caneca' },
  { name: 'Caderno' },
  { name: 'Tequila José Cuervo' },
  { name: 'Apagador' },
  { name: 'Controle da TV' },
  { name: 'Estrela azul da Neoassist' },
  { name: 'Cortador de unha' }])

Place.create([{ name: 'Mesinha de concreto da escada' },
  { name: 'Frente da guarita do Morgan Freeman' },
  { name: 'Puffs' },
  { name: 'Sala da Elaine' },
  { name: 'Atrás do Portinho' },
  { name: 'Sala de reunião' },
  { name: 'Frente do ponto' },
  { name: 'Salinha do time de produto' },
  { name: 'Copa' },
  { name: 'Quiet-Room' },
  { name: 'Escada da porta de entrada' },
  { name: 'Mesa de pingue pongue' },
  { name: 'Escada de incêndio' }])
